SELECT SUM(B.SCORE) AS SCORE, 
       A.EMP_NO AS EMP_NO, 
       A.EMP_NAME AS EMP_NAME, 
       A.POSITION AS POSITION, 
       A.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS A
JOIN HR_GRADE AS B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
HAVING SUM(B.SCORE) = (
    SELECT MAX(total_score)
    FROM (
        SELECT SUM(B2.SCORE) AS total_score
        FROM HR_EMPLOYEES AS A2
        JOIN HR_GRADE AS B2 ON A2.EMP_NO = B2.EMP_NO
        GROUP BY A2.EMP_NO
    ) sub
)
ORDER BY SCORE DESC;
