SELECT SUM(CF) AS FISH_COUNT 
FROM
    (
    SELECT A.FISH_TYPE, COUNT(A.FISH_TYPE) AS CF
    FROM FISH_INFO AS A
        JOIN FISH_NAME_INFO AS B
        ON A.FISH_TYPE = B.FISH_TYPE
    WHERE B.FISH_NAME = 'BASS' OR B.FISH_NAME = 'SNAPPER'
    GROUP BY A.FISH_TYPE
    ) SUB
;