SELECT 
    A.TITLE, -- 게시글 제목
    A.BOARD_ID, -- 게시글 ID
    B.REPLY_ID, -- 댓글 아이디
    B.WRITER_ID, -- 댓글 작성자 아이디
    B.CONTENTS,  -- 댓글 내용
    DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE -- 댓글 작성일
FROM 
    USED_GOODS_BOARD AS A
INNER JOIN 
    USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE 
    YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10
ORDER BY 
    B.CREATED_DATE ASC, 
    A.TITLE ASC;