SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT SC.CODE FROM SKILLCODES SC WHERE SC.NAME = 'Python')) != 0
   OR (SKILL_CODE & (SELECT SC.CODE FROM SKILLCODES SC WHERE SC.NAME = 'C#')) != 0
ORDER BY ID;
